name: Publish the package to GPR (from release)

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Authenticates packages to push to GPR
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/alexeyvyduykin/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build
      run: dotnet build src/Mapsui.Interactivity/Mapsui.Interactivity.csproj
    - name: Build
      run: dotnet build src/Mapsui.Interactivity.UI/Mapsui.Interactivity.UI.csproj
    - name: Build
      run: dotnet build src/Mapsui.Interactivity.UI.Avalonia/Mapsui.Interactivity.UI.Avalonia.csproj
      
    - name: Create the package
      run: dotnet pack --configuration Release src/Mapsui.Interactivity/Mapsui.Interactivity.csproj
    - name: Create the package
      run: dotnet pack --configuration Release src/Mapsui.Interactivity.UI/Mapsui.Interactivity.UI.csproj
    - name: Create the package
      run: dotnet pack --configuration Release src/Mapsui.Interactivity.UI.Avalonia/Mapsui.Interactivity.UI.Avalonia.csproj
      
    - name: Publish the package to GPR
      run: dotnet nuget push src/Mapsui.Interactivity/bin/Release/*.nupkg --skip-duplicate
    - name: Publish the package to GPR
      run: dotnet nuget push src/Mapsui.Interactivity.UI/bin/Release/*.nupkg --skip-duplicate
    - name: Publish the package to GPR
      run: dotnet nuget push src/Mapsui.Interactivity.UI.Avalonia/bin/Release/*.nupkg --skip-duplicate
